name: Install Frida Devkit
description: Install Frida Devkit
inputs:
  arch:
    required: true
    path: the architecture of the devkit
  os:
    required: true
    path: the target operating system of the devkit
  version:
    required: true
    path: the version of the devkit
  outdir:
    required: true
    path: where to save header and dylib
runs:
  using: composite
  steps:
    - run: |
        mkdir /tmp/frida-core-devkit && cd /tmp/frida-core-devkit
        wget https://github.com/frida/frida/releases/download/${{ inputs.version }}/frida-core-devkit-${{ inputs.version }}-${{ inputs.os }}-${{ inputs.arch }}.tar.xz -O - | tar --extract --xz
        mkdir -p ${{ inputs.outdir }}/include
        mkdir -p ${{ inputs.outdir }}/lib
        cp frida-core.h ${{ inputs.outdir }}/include
        cp libfrida-core.* ${{ inputs.outdir }}/lib
        rm -rf /tmp/frida-core-devkit
      shell: bash
